- "Hey **{{name}}**, a wild bone appears. It's super effective!"
- "Bone hits **{{name}}** for 152 Fire Damage. (critical)"
- "Bones días, Bonegiorno and Bonejour! Do you see where this is heading, **{{name}}**?"
- "Is it a bird? Is it a plane? No, it's a bone flying towards **{{name}}**!"
- "Hey **{{name}}**, you caught a bone! What a good boy!"
- "You didn't choose the bone - the bone chose you, **{{name}}**."
- "You, **{{name}}**, are amongst the chosen bearers of the bone."
- "Roses are red, Violets are blue, hey **{{name}}**, here's a bone for you."
- "**{{name}}** picks up Valorous Battle Bone of Iron Will. 1 Hand. 200 Gold. -5 to Run Away."
- "By the power of the bone, **{{name}}** may speak!"
- "**{{name}}**, take this bone as a sign of appreciation."
- "With great bone comes great responsibility. Use this bone wisely, **{{name}}**."
